pipeline{
  
  agent any

  // timestamps


  // environment
  environment {
    ENV = "dev"
  }

  stages{

    // chekout git scm 
    stage("git checkout"){
      steps{
        checkout scm
      }
    }

    // Build Stage, compile and build application, and fail fast if code is broken
    stage("Build"){
      
      steps{
        echo "Compile and Build appliation Env $ENV"
        sh "echo Build Successfull"
//java: sh mvn clean package
//node: sh npm run build	
      }
 
    }

    // unit test stage
    stage("Unit Test"){
      steps{
        sh "date"
        sh "cal"
        echo "Running Testing stage"
        sh "echo Unit tests passed"
      }
    }

    // static code anyalysis, it check code quality
    stage("Static Code Analysis"){
      steps{
        echo "Running code Quality Scan"
        sh "echo sonar scan completed"
      }
    }

    // Security Scan
    stage("Security Scan"){
      steps{
        echo "Running Security Scan"
        sh "echo no velnerabilities found"
      }
    }

    // create Artifacts
    stage("Package Artifacts"){
      steps{
        echo "packaging artifacts appliation"
      }
    }

    // push artifacts
    stage("Push Artifacts"){
      steps{
        echo "Push Artifacts to registry"
      }
    }

    // deploy stage
    stage("Deploy"){
      steps{
        echo "Deploying to dev environment"
      }
    }

  }

  // post build action
  post{

    // all stages passed
    success {
      echo "Pipeline Completed successfully."
    }    

    // if any stage failed
    failure {
      echo "Pipeline Failed"
    }
   
    // unstable pipeline test quality issue
    unstable {
      echo "Pipeline Unstable"
    }

    // always clean up
    always {
      echo "Cleaning Workspace"
      cleanWs()
    }
   
  }

}
