pipeline{
  
  agent any

  // timestamps


  stages{

    // chekout git scm 
    stage("git checkout"){
      steps{
        checkout scm
      }
    }

    // test stage
    stage("Build"){
      
      steps{
        echo "Build Job"
      }
 
    }
    // test stage

    stage("Test"){
      steps{
        sh "date"
        sh "cal"
        echo "Testing stage"
      }
    }

    // deploy stage
    stage("Deploy"){
      steps{
        echo "Deploying stage"
      }
    }

  }

}
